# app/upgrades/pro_config.py

TREND_SLOPE_LOOKBACK = 8
MIN_TREND_SLOPE_STRENGTH = 0.15

MIN_BREAKOUT_CLOSE_ATR = 0.20
MIN_RETEST_HOLD_ATR = 0.15

MIN_SWEEP_REJECTION_BODY_RATIO = 0.35
MIN_SWEEP_WICK_TO_BODY = 1.8

ZONE_REACTION_LOOKBACK = 80
MIN_ZONE_TOUCHES = 2

MOMENTUM_DISPLACEMENT_ATR = 0.6
MAX_CHASE_DISTANCE_ATR = 0.8

RANGE_ATR_THRESHOLD = 1.2
TREND_ATR_THRESHOLD = 2.0

NO_TRADE_IF_SIDEWAYS = True
NO_TRADE_IF_WEAK_BREAKOUT = True
NO_TRADE_IF_LOW_SESSION_AND_WEAK_MOMENTUM = True